<?php

namespace Database\Seeders;

use App\Models\Dua;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DuaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $duas = [
            [
                'title' => 'Rabbana Atina fid-Dunya Hasanah (Comprehensive Dua for Good in Both Worlds)',
                'slug' => 'rabbana-atina-fid-dunya-hasanah',
                'category' => 'Comprehensive & Success',
                'description' => 'The most frequently recited supplication of Prophet Muhammad ﷺ according to Anas ibn Malik (RA). It encompasses all worldly welfare (health, sustenance, righteous family, peace) and all eternal bliss (forgiveness, safety from the Hellfire, Paradise).',
                'arabic_text' => 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
                'transliteration' => 'Rabbanā ātinā fī l-dunyā ḥasanatan wa-fī l-ākhirati ḥasanatan wa-qinā ‘adhāba l-nār',
                'translation_en' => 'Our Lord, give us in this world that which is good and in the Hereafter that which is good, and protect us from the punishment of the Fire.',
                'translation_ur' => 'اے ہمارے رب! ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما، اور ہمیں آگ کے عذاب سے بچا۔',
                'word_by_word' => [
                    ['arabic' => 'رَبَّنَا', 'transliteration' => 'Rabbanā', 'meaning_en' => 'Our Lord', 'meaning_ur' => 'اے ہمارے رب'],
                    ['arabic' => 'آتِنَا', 'transliteration' => 'ātinā', 'meaning_en' => 'Grant us', 'meaning_ur' => 'ہمیں عطا فرما'],
                    ['arabic' => 'فِي', 'transliteration' => 'fī', 'meaning_en' => 'in', 'meaning_ur' => 'میں'],
                    ['arabic' => 'الدُّنْيَا', 'transliteration' => 'l-dunyā', 'meaning_en' => 'the worldly life', 'meaning_ur' => 'دنیا'],
                    ['arabic' => 'حَسَنَةً', 'transliteration' => 'ḥasanatan', 'meaning_en' => 'good / excellence', 'meaning_ur' => 'بھلائی'],
                    ['arabic' => 'وَفِي', 'transliteration' => 'wa-fī', 'meaning_en' => 'and in', 'meaning_ur' => 'اور میں'],
                    ['arabic' => 'الْآخِرَةِ', 'transliteration' => 'l-ākhirati', 'meaning_en' => 'the Hereafter', 'meaning_ur' => 'آخرت'],
                    ['arabic' => 'حَسَنَةً', 'transliteration' => 'ḥasanatan', 'meaning_en' => 'good / paradise', 'meaning_ur' => 'بھلائی'],
                    ['arabic' => 'وَقِنَا', 'transliteration' => 'wa-qinā', 'meaning_en' => 'and save / protect us', 'meaning_ur' => 'اور ہمیں بچا'],
                    ['arabic' => 'عَذَابَ', 'transliteration' => '‘adhāba', 'meaning_en' => 'from the torment of', 'meaning_ur' => 'عذاب سے'],
                    ['arabic' => 'النَّارِ', 'transliteration' => 'l-nār', 'meaning_en' => 'the Fire', 'meaning_ur' => 'آگ کے'],
                ],
                'meaning_explanation' => 'The word "Ḥasanah" (حَسَنَة) in Arabic is an all-inclusive term. In the worldly context, classical scholars such as Ibn Kathir and Al-Qurtubi noted it includes lawful sustenance, beneficial knowledge, a righteous spouse, good health, and peace of mind. In the Hereafter, Ḥasanah means ease during the Reckoning, entry into Jannat al-Firdaws, and looking upon the Countenance of Allah. "Wa-qinā ‘adhāb an-nār" seeks divine shielding from spiritual destruction.',
                'benefits_and_virtues' => 'Anas (RA) reported: "The supplication the Prophet ﷺ made most frequently was: Rabbana atina fid-dunya hasanah..." (Sahih al-Bukhari 4522, Sahih Muslim 2690). Reciting it during Tawaf, after Salah, and during any moment of acceptance brings comprehensive barakah.',
                'when_to_recite' => 'During Tawaf, after obligatory prayers, during moments of acceptance, and in daily remembrance',
                'repeat_count' => 3,
                'source_type' => 'both',
                'quran_reference' => 'Surah Al-Baqarah (2:201)',
                'surah_number' => 2,
                'verse_number' => 201,
                'hadith_reference' => 'Sahih al-Bukhari 4522; Sahih Muslim 2690',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '4522',
                'hadith_grading' => 'Muttafaq ‘Alayh (Sahih)',
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'title' => 'Sayyid al-Istighfar (The Master Supplication for Forgiveness)',
                'slug' => 'sayyid-al-istighfar',
                'category' => 'Forgiveness & Tawbah',
                'description' => 'The supreme pinnacle of asking for forgiveness taught by Prophet Muhammad ﷺ. It establishes pure monotheism, acknowledges servantship, confesses divine favors, and humbles oneself with total admission of shortcoming.',
                'arabic_text' => 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
                'transliteration' => 'Allāhumma anta Rabbī lā ilāha illā anta, khalaqtanī wa-anā ‘abduka, wa-anā ‘alā ‘ahdika wa-wa‘dika ma-staṭa‘tu, a‘ūdhu bika min sharri mā ṣana‘tu, abū’u laka bi-ni‘matika ‘alayya, wa-abū’u laka bi-dhanbī fa-ghfir lī fa-innahu lā yaghfiru l-dhunūba illā anta',
                'translation_en' => 'O Allah, You are my Lord; there is no deity worthy of worship except You. You created me, and I am Your servant, and I uphold Your covenant and Your promise as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your blessings upon me, and I confess my sins to You; so forgive me, for indeed none forgives sins except You.',
                'translation_ur' => 'اے اللہ! تو ہی میرا پروردگار ہے، تیرے سوا کوئی معبود نہیں۔ تو نے ہی مجھے پیدا کیا اور میں تیرا بندہ ہوں، اور میں اپنی استطاعت کے مطابق تیرے عہد اور وعدے پر قائم ہوں۔ میں اپنے کیے کے شر سے تیری پناہ مانگتا ہوں، اپنے اوپر تیری نعمتوں کا اقرار کرتا ہوں اور اپنے گناہوں کا اعتراف کرتا ہوں۔ پس مجھے بخش دے، کیونکہ تیرے سوا کوئی گناہوں کو معاف نہیں کر سکتا۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'أَنْتَ', 'transliteration' => 'anta', 'meaning_en' => 'You are', 'meaning_ur' => 'تو ہے'],
                    ['arabic' => 'رَبِّي', 'transliteration' => 'Rabbī', 'meaning_en' => 'my Lord', 'meaning_ur' => 'میرا رب'],
                    ['arabic' => 'لَا إِلَهَ', 'transliteration' => 'lā ilāha', 'meaning_en' => 'there is no deity', 'meaning_ur' => 'کوئی معبود نہیں'],
                    ['arabic' => 'إِلَّا أَنْتَ', 'transliteration' => 'illā anta', 'meaning_en' => 'except You', 'meaning_ur' => 'سوائے تیرے'],
                    ['arabic' => 'خَلَقْتَنِي', 'transliteration' => 'khalaqtanī', 'meaning_en' => 'You created me', 'meaning_ur' => 'تو نے مجھے پیدا کیا'],
                    ['arabic' => 'وَأَنَا عَبْدُكَ', 'transliteration' => 'wa-anā ‘abduka', 'meaning_en' => 'and I am Your servant', 'meaning_ur' => 'اور میں تیرا بندہ ہوں'],
                    ['arabic' => 'وَأَنَا عَلَى عَهْدِكَ', 'transliteration' => 'wa-anā ‘alā ‘ahdika', 'meaning_en' => 'and I am upon Your covenant', 'meaning_ur' => 'اور میں تیرے عہد پر ہوں'],
                    ['arabic' => 'وَوَعْدِكَ', 'transliteration' => 'wa-wa‘dika', 'meaning_en' => 'and Your promise', 'meaning_ur' => 'اور تیرے وعدے پر'],
                    ['arabic' => 'مَا اسْتَطَعْتُ', 'transliteration' => 'ma-staṭa‘tu', 'meaning_en' => 'as much as I can', 'meaning_ur' => 'اپنی استطاعت بھر'],
                    ['arabic' => 'أَعُوذُ بِكَ', 'transliteration' => 'a‘ūdhu bika', 'meaning_en' => 'I seek refuge in You', 'meaning_ur' => 'میں تیری پناہ لیتا ہوں'],
                    ['arabic' => 'مِنْ شَرِّ مَا صَنَعْتُ', 'transliteration' => 'min sharri mā ṣana‘tu', 'meaning_en' => 'from evil of what I did', 'meaning_ur' => 'اپنے کیے کے شر سے'],
                    ['arabic' => 'أَبُوءُ لَكَ', 'transliteration' => 'abū’u laka', 'meaning_en' => 'I acknowledge to You', 'meaning_ur' => 'میں تیرے حضور اقرار کرتا ہوں'],
                    ['arabic' => 'بِنِعْمَتِكَ عَلَيَّ', 'transliteration' => 'bi-ni‘matika ‘alayya', 'meaning_en' => 'Your blessings on me', 'meaning_ur' => 'تیری نعمت کا جو مجھ پر ہے'],
                    ['arabic' => 'وَأَبُوءُ بِذَنْبِي', 'transliteration' => 'wa-abū’u bi-dhanbī', 'meaning_en' => 'and I admit my sins', 'meaning_ur' => 'اور اپنے گناہ کا اعتراف کرتا ہوں'],
                    ['arabic' => 'فَاغْفِرْ لِي', 'transliteration' => 'fa-ghfir lī', 'meaning_en' => 'so forgive me', 'meaning_ur' => 'پس مجھے معاف فرما'],
                    ['arabic' => 'لَا يَغْفِرُ الذُّنُوبَ', 'transliteration' => 'lā yaghfiru l-dhunūba', 'meaning_en' => 'none forgives sins', 'meaning_ur' => 'نہیں بخشتا گناہوں کو'],
                    ['arabic' => 'إِلَّا أَنْتَ', 'transliteration' => 'illā anta', 'meaning_en' => 'except You', 'meaning_ur' => 'سوائے تیرے'],
                ],
                'meaning_explanation' => 'Imam Ibn al-Qayyim highlighted that this Dua combines five essential pillars of repentance: Tawhid (Oneness of Allah), Uboodiyyah (servitude), recognition of divine covenants, profound gratitude for blessings, and sincere repentance for flaws. The phrase "Abū’u" (أَبُوءُ) indicates returning to Allah with utter honesty, holding divine grace on one shoulder and human deficiency on the other.',
                'benefits_and_virtues' => 'The Prophet ﷺ said: "Whoever recites it during the day with firm faith and dies before evening will be among the people of Paradise; and whoever recites it at night with firm faith and dies before morning will be among the people of Paradise." (Sahih al-Bukhari 6306).',
                'when_to_recite' => 'Every morning after Fajr and every evening after Asr/Maghrib',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih al-Bukhari 6306 (Book 80, Hadith 3)',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '6306',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'title' => 'Ayat e Karima — Dua of Prophet Yunus (AS) in Distress',
                'slug' => 'ayat-e-karima-prophet-yunus',
                'category' => 'Distress & Hardship',
                'description' => 'The cry of Prophet Yunus (Jonah) AS from the darkness of the whale belly in the depths of the ocean. It combines the affirmation of Tawhid, the glorification of Allah above all shortcomings, and the confession of one’s own wrongdoing.',
                'arabic_text' => 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
                'transliteration' => 'Lā ilāha illā anta subḥānaka innī kuntu mina l-ẓālimīn',
                'translation_en' => 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
                'translation_ur' => 'تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ہی قصورواروں میں سے تھا۔',
                'word_by_word' => [
                    ['arabic' => 'لَّا إِلَٰهَ', 'transliteration' => 'Lā ilāha', 'meaning_en' => 'There is no deity', 'meaning_ur' => 'کوئی معبود نہیں'],
                    ['arabic' => 'إِلَّا أَنتَ', 'transliteration' => 'illā anta', 'meaning_en' => 'except You', 'meaning_ur' => 'سوائے تیرے'],
                    ['arabic' => 'سُبْحَانَكَ', 'transliteration' => 'subḥānaka', 'meaning_en' => 'glory be to You', 'meaning_ur' => 'تو پاک ہے'],
                    ['arabic' => 'إِنِّي كُنتُ', 'transliteration' => 'innī kuntu', 'meaning_en' => 'indeed I was / have been', 'meaning_ur' => 'بے شک میں تھا'],
                    ['arabic' => 'مِنَ الظَّالِمِينَ', 'transliteration' => 'mina l-ẓālimīn', 'meaning_en' => 'among the wrongdoers', 'meaning_ur' => 'ظالموں میں سے'],
                ],
                'meaning_explanation' => 'Subḥānaka (سُبْحَانَكَ) purifies Allah from any injustice, signifying that whatever trial afflicts the servant is never unjust on Allah’s part, but a result of human imperfection. Acknowledging "innī kuntu mina l-ẓālimīn" lifts the veil of arrogance and attracts instant divine mercy and relief from severe hardships.',
                'benefits_and_virtues' => 'Prophet Muhammad ﷺ declared: "No Muslim supplicates with this prayer for anything whatsoever except that Allah answers him." (Jami‘ at-Tirmidhi 3505; Sunan an-Nasa’i al-Kubra 10492). Verified as Sahih by Al-Albani.',
                'when_to_recite' => 'During anxiety, grief, trials, depression, difficult moments, and when seeking immediate divine rescue',
                'repeat_count' => 40,
                'source_type' => 'both',
                'quran_reference' => 'Surah Al-Anbiya (21:87)',
                'surah_number' => 21,
                'verse_number' => 87,
                'hadith_reference' => 'Jami‘ at-Tirmidhi 3505; Musnad Ahmad 1462',
                'hadith_book' => 'Jami‘ at-Tirmidhi',
                'hadith_number' => '3505',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 3,
            ],
            [
                'title' => 'Dua for Parents (Mercy and Kindness in Old Age)',
                'slug' => 'dua-for-parents-mercy',
                'category' => 'Parents & Family',
                'description' => 'The divine prayer prescribed in the Quran to lower the wing of humility and pray for boundless mercy for one’s mother and father, recalling their tender care during childhood.',
                'arabic_text' => 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
                'transliteration' => 'Rabbi r-ḥamhumā kamā rabbayānī ṣaghīrā',
                'translation_en' => 'My Lord, have mercy upon them as they brought me up when I was small.',
                'translation_ur' => 'اے میرے رب! ان دونوں پر رحم فرما جیسا کہ انہوں نے بچپن میں میری پرورش فرمائی۔',
                'word_by_word' => [
                    ['arabic' => 'رَّبِّ', 'transliteration' => 'Rabbi', 'meaning_en' => 'My Lord', 'meaning_ur' => 'اے میرے رب'],
                    ['arabic' => 'ارْحَمْهُمَا', 'transliteration' => 'r-ḥamhumā', 'meaning_en' => 'have mercy on both of them', 'meaning_ur' => 'ان دونوں پر رحم فرما'],
                    ['arabic' => 'كَمَا', 'transliteration' => 'kamā', 'meaning_en' => 'just as', 'meaning_ur' => 'جیسا کہ'],
                    ['arabic' => 'رَبَّيَانِي', 'transliteration' => 'rabbayānī', 'meaning_en' => 'they nurtured & raised me', 'meaning_ur' => 'انہوں نے مجھے پالا'],
                    ['arabic' => 'صَغِيرًا', 'transliteration' => 'ṣaghīrā', 'meaning_en' => 'when I was small', 'meaning_ur' => 'چھوٹے ہوتے ہوئے'],
                ],
                'meaning_explanation' => 'The root R-B-W in "rabbayānī" (رَبَّيَانِي) implies holistic cultivation—physical, spiritual, and emotional care requiring patience and self-sacrifice. Praying for Allah’s Rahmah (Mercy) repays their sleepless nights with eternal divine compassion.',
                'benefits_and_virtues' => 'Abu Hurairah (RA) reported that the Prophet ﷺ said: "When a person dies, all their deeds end except three: continuous charity, beneficial knowledge, or a righteous child who prays for them." (Sahih Muslim 1631).',
                'when_to_recite' => 'In every Salah, after Tashahhud, in prostration, and throughout daily life for parents alive or deceased',
                'repeat_count' => 3,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Al-Isra (17:24)',
                'surah_number' => 17,
                'verse_number' => 24,
                'hadith_reference' => 'Sahih Muslim 1631',
                'hadith_book' => 'Sahih Muslim',
                'hadith_number' => '1631',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 4,
            ],
            [
                'title' => 'Rabbi Zidni ‘Ilma (Dua for Growth in Knowledge and Wisdom)',
                'slug' => 'rabbi-zidni-ilma-knowledge',
                'category' => 'Guidance & Knowledge',
                'description' => 'The only worldly or spiritual asset Allah directly commanded His noble Prophet Muhammad ﷺ to pray for an increase in is knowledge (‘Ilm).',
                'arabic_text' => 'رَّبِّ زِدْنِي عِلْمًا',
                'transliteration' => 'Rabbi zidnī ‘ilmā',
                'translation_en' => 'My Lord, increase me in knowledge.',
                'translation_ur' => 'اے میرے پروردگار! مجھے علم میں اضافہ عطا فرما۔',
                'word_by_word' => [
                    ['arabic' => 'رَّبِّ', 'transliteration' => 'Rabbi', 'meaning_en' => 'My Lord', 'meaning_ur' => 'اے میرے پروردگار'],
                    ['arabic' => 'زِدْنِي', 'transliteration' => 'zidnī', 'meaning_en' => 'increase me', 'meaning_ur' => 'مجھے زیادہ فرما'],
                    ['arabic' => 'عِلْمًا', 'transliteration' => '‘ilmā', 'meaning_en' => 'in knowledge', 'meaning_ur' => 'علم میں'],
                ],
                'meaning_explanation' => '‘Ilm in Islamic theology refers to authentic understanding of the Creator, His divine laws, revelation, and beneficial insight that translates directly into righteous action and humility.',
                'benefits_and_virtues' => 'Prophet Muhammad ﷺ said: "Whoever travels a path in search of knowledge, Allah makes easy for him a path to Paradise." (Sahih Muslim 2699).',
                'when_to_recite' => 'Before studying, attending lectures, seeking guidance, and during daily work',
                'repeat_count' => 7,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Ta-Ha (20:114)',
                'surah_number' => 20,
                'verse_number' => 114,
                'hadith_reference' => 'Sahih Muslim 2699',
                'hadith_book' => 'Sahih Muslim',
                'hadith_number' => '2699',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 5,
            ],
            [
                'title' => 'Dua of Prophet Musa (AS) for Ease, Courage, and Eloquent Speech',
                'slug' => 'prophet-musa-ease-speech',
                'category' => 'Distress & Hardship',
                'description' => 'Supplicated by Prophet Musa (Moses) AS when commanded to confront Pharaoh. It asks for emotional tranquility, the unwinding of obstacles, and clarity of articulation.',
                'arabic_text' => 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي',
                'transliteration' => 'Rabbi-shraḥ lī ṣadrī, wa-yassir lī amrī, wa-ḥlul ‘uqdatam-min lisānī, yafqahū qawlī',
                'translation_en' => 'My Lord, expand for me my chest [with reassurance], and ease for me my task, and untie the knot from my tongue, that they may understand my speech.',
                'translation_ur' => 'اے میرے رب! میرے لیے میرا سینہ کھول دے، اور میرے لیے میرا کام آسان فرما دے، اور میری زبان کی گرہ کھول دے تاکہ وہ میری بات سمجھ سکیں۔',
                'word_by_word' => [
                    ['arabic' => 'رَبِّ', 'transliteration' => 'Rabbi', 'meaning_en' => 'My Lord', 'meaning_ur' => 'اے میرے رب'],
                    ['arabic' => 'اشْرَحْ لِي', 'transliteration' => 'shraḥ lī', 'meaning_en' => 'expand for me', 'meaning_ur' => 'میرے لیے کشادہ فرما'],
                    ['arabic' => 'صَدْرِي', 'transliteration' => 'ṣadrī', 'meaning_en' => 'my chest / heart', 'meaning_ur' => 'میرا سینہ'],
                    ['arabic' => 'وَيَسِّرْ لِي', 'transliteration' => 'wa-yassir lī', 'meaning_en' => 'and make easy for me', 'meaning_ur' => 'اور آسان فرما میرے لیے'],
                    ['arabic' => 'أَمْرِي', 'transliteration' => 'amrī', 'meaning_en' => 'my task / mission', 'meaning_ur' => 'میرا کام'],
                    ['arabic' => 'وَاحْلُلْ', 'transliteration' => 'wa-ḥlul', 'meaning_en' => 'and untie / loosen', 'meaning_ur' => 'اور کھول دے'],
                    ['arabic' => 'عُقْدَةً', 'transliteration' => '‘uqdatan', 'meaning_en' => 'the knot / impediment', 'meaning_ur' => 'گرہ'],
                    ['arabic' => 'مِّن لِّسَانِي', 'transliteration' => 'min lisānī', 'meaning_en' => 'from my tongue', 'meaning_ur' => 'میری زبان سے'],
                    ['arabic' => 'يَفْقَهُوا', 'transliteration' => 'yafqahū', 'meaning_en' => 'so they understand deeply', 'meaning_ur' => 'تاکہ وہ سمجھ سکیں'],
                    ['arabic' => 'قَوْلِي', 'transliteration' => 'qawlī', 'meaning_en' => 'my speech / words', 'meaning_ur' => 'میری بات'],
                ],
                'meaning_explanation' => 'Expanding the chest ("Sharh as-Sadr") signifies spiritual fortitude, tolerance, and liberation from anxiety. Unknotting the tongue allows truth to penetrate the hearts of listeners clearly.',
                'benefits_and_virtues' => 'Revealed in Surah Ta-Ha verses 25-28, this prayer was answered immediately by Allah: "You have been granted your request, O Moses." (20:36). Ideal for public speaking, exams, interviews, and interpersonal conflicts.',
                'when_to_recite' => 'Before speaking in public, job interviews, presentations, exams, or facing intimidation',
                'repeat_count' => 3,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Ta-Ha (20:25-28)',
                'surah_number' => 20,
                'verse_number' => 25,
                'hadith_reference' => null,
                'hadith_book' => null,
                'hadith_number' => null,
                'hadith_grading' => null,
                'is_featured' => true,
                'order' => 6,
            ],
            [
                'title' => 'Dua for Protection from Anxiety, Grief, Weakness, and Debt',
                'slug' => 'protection-anxiety-grief-debt',
                'category' => 'Distress & Hardship',
                'description' => 'A daily shield taught by the Prophet ﷺ against eight crippling psychological, physical, and financial burdens.',
                'arabic_text' => 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ، وَغَلَبَةِ الرِّجَالِ',
                'transliteration' => 'Allāhumma innī a‘ūdhu bika mina l-hammi wa-l-ḥazani, wa-l-‘ajzi wa-l-kasali, wa-l-bukhli wa-l-jubni, wa-ḍala‘i l-dayni, wa-ghalabati l-rijāl',
                'translation_en' => 'O Allah, I seek refuge in You from anxiety and sorrow, from weakness and laziness, from miserliness and cowardice, from being overcome by debt and being overpowered by men.',
                'translation_ur' => 'اے اللہ! میں تیری پناہ مانگتا ہوں تفکرات اور رنج و غم سے، عاجزی اور سستی سے، بخل اور بزدلی سے، قرض کے بوجھ تلے دبنے سے اور لوگوں کے تسلط سے۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'إِنِّي أَعُوذُ بِكَ', 'transliteration' => 'innī a‘ūdhu bika', 'meaning_en' => 'I seek refuge in You', 'meaning_ur' => 'میں تیری پناہ مانگتا ہوں'],
                    ['arabic' => 'مِنَ الْهَمِّ', 'transliteration' => 'mina l-hammi', 'meaning_en' => 'from anxiety (about future)', 'meaning_ur' => 'فکر اور اندیشے سے'],
                    ['arabic' => 'وَالْحَزَنِ', 'transliteration' => 'wa-l-ḥazani', 'meaning_en' => 'and sorrow (about past)', 'meaning_ur' => 'اور غم سے'],
                    ['arabic' => 'وَالْعَجْزِ', 'transliteration' => 'wa-l-‘ajzi', 'meaning_en' => 'and incapacity / weakness', 'meaning_ur' => 'اور بے بسی سے'],
                    ['arabic' => 'وَالْكَسَلِ', 'transliteration' => 'wa-l-kasali', 'meaning_en' => 'and laziness / procrastination', 'meaning_ur' => 'اور سستی سے'],
                    ['arabic' => 'وَالْبُخْلِ', 'transliteration' => 'wa-l-bukhli', 'meaning_en' => 'and stinginess / greed', 'meaning_ur' => 'اور کنجوسی سے'],
                    ['arabic' => 'وَالْجُبْنِ', 'transliteration' => 'wa-l-jubni', 'meaning_en' => 'and cowardice', 'meaning_ur' => 'اور بزدلی سے'],
                    ['arabic' => 'وَضَلَعِ الدَّيْنِ', 'transliteration' => 'wa-ḍala‘i l-dayni', 'meaning_en' => 'and heavy burden of debt', 'meaning_ur' => 'اور قرض کے بوجھ سے'],
                    ['arabic' => 'وَغَلَبَةِ الرِّجَالِ', 'transliteration' => 'wa-ghalabati l-rijāl', 'meaning_en' => 'and oppression of men', 'meaning_ur' => 'اور لوگوں کے غلبے سے'],
                ],
                'meaning_explanation' => 'Scholars note that Al-Hamm (الْهَمّ) is anxiety regarding upcoming uncertainties, while Al-Ḥazan (الْحَزَن) is grief over past losses. Al-‘Ajz (الْعَجْز) is the inability to act despite wanting to, while Al-Kasal (الْكَسَل) is having capacity but lacking motivation.',
                'benefits_and_virtues' => 'Anas ibn Malik (RA) reported: "I used to serve the Messenger of Allah ﷺ whenever he stayed at home, and I repeatedly heard him supplicating with these words." (Sahih al-Bukhari 2893, 6363).',
                'when_to_recite' => 'Every morning and evening, and in times of financial or emotional distress',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih al-Bukhari 2893 (Book 56, Hadith 108)',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '2893',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 7,
            ],
            [
                'title' => 'Ya Muqallibal Quloob (Dua for Steadfastness of Heart in Faith)',
                'slug' => 'steadfastness-heart-faith',
                'category' => 'Guidance & Knowledge',
                'description' => 'The supplication recited constantly by the Prophet ﷺ to safeguard the human heart from deviance, cynicism, and loss of faith.',
                'arabic_text' => 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ',
                'transliteration' => 'Yā Muqalliba l-qulūbi thabbit qalbī ‘alā dīnik',
                'translation_en' => 'O Turner of the hearts, keep my heart firm upon Your religion.',
                'translation_ur' => 'اے دلوں کو پھیرنے والے! میرے دل کو اپنے دین پر ثابت قدم رکھ۔',
                'word_by_word' => [
                    ['arabic' => 'يَا مُقَلِّبَ', 'transliteration' => 'Yā Muqalliba', 'meaning_en' => 'O Turner / Transformer', 'meaning_ur' => 'اے پھیرنے والے'],
                    ['arabic' => 'الْقُلُوبِ', 'transliteration' => 'l-qulūbi', 'meaning_en' => 'of the hearts', 'meaning_ur' => 'دلوں کے'],
                    ['arabic' => 'ثَبِّتْ', 'transliteration' => 'thabbit', 'meaning_en' => 'make firm / steady', 'meaning_ur' => 'ثابت رکھ'],
                    ['arabic' => 'قَلْبِي', 'transliteration' => 'qalbī', 'meaning_en' => 'my heart', 'meaning_ur' => 'میرا دل'],
                    ['arabic' => 'عَلَى دِينِكَ', 'transliteration' => '‘alā dīnika', 'meaning_en' => 'upon Your religion / path', 'meaning_ur' => 'اپنے دین پر'],
                ],
                'meaning_explanation' => 'The Arabic word for heart, "Qalb" (قَلْب), stems from the root indicating frequent flipping and changing. The hearts of humanity are between two of the fingers of the Most Merciful; He turns them as He wills (Sahih Muslim 2654). Supplicating with this divine name anchors spiritual steadfastness.',
                'benefits_and_virtues' => 'Umm Salamah (RA) was asked: "What was the supplication the Messenger of Allah ﷺ made most frequently in your house?" She replied: "Ya Muqallibal Quloob..." (Jami‘ at-Tirmidhi 3522).',
                'when_to_recite' => 'Daily, during Sujud in prayer, and during times of spiritual doubt or societal fitnah',
                'repeat_count' => 3,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Jami‘ at-Tirmidhi 3522; Sunan Ibn Majah 3834',
                'hadith_book' => 'Jami‘ at-Tirmidhi',
                'hadith_number' => '3522',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 8,
            ],
            [
                'title' => 'Bismillahilladhi La Yadurru (Morning & Evening Shield Against Harm)',
                'slug' => 'morning-evening-shield-against-harm',
                'category' => 'Morning & Evening',
                'description' => 'A powerful protective formula against any sudden affliction, poison, disease, or evil in the heavens and the earth.',
                'arabic_text' => 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
                'transliteration' => 'Bismi-llāhi-lladhī lā yaḍurru ma‘a-smihī shay’un fī l-arḍi wa-lā fī l-samā’i wa-huwa l-Samī‘u l-‘Alīm',
                'translation_en' => 'In the Name of Allah, with Whose Name nothing can cause harm in the earth nor in the heavens, and He is the All-Hearing, the All-Knowing.',
                'translation_ur' => 'اللہ کے نام کے ساتھ جس کے نام کی برکت سے زمین اور آسمان میں کوئی چیز نقصان نہیں پہنچا سکتی، اور وہی سب کچھ سننے والا اور جاننے والا ہے۔',
                'word_by_word' => [
                    ['arabic' => 'بِسْمِ اللَّهِ', 'transliteration' => 'Bismi-llāhi', 'meaning_en' => 'In the name of Allah', 'meaning_ur' => 'اللہ کے نام سے'],
                    ['arabic' => 'الَّذِي', 'transliteration' => 'alladhī', 'meaning_en' => 'the One Who', 'meaning_ur' => 'وہ ذات جو'],
                    ['arabic' => 'لَا يَضُرُّ', 'transliteration' => 'lā yaḍurru', 'meaning_en' => 'cannot harm', 'meaning_ur' => 'نقصان نہیں پہنچا سکتی'],
                    ['arabic' => 'مَعَ اسْمِهِ', 'transliteration' => 'ma‘a-smihī', 'meaning_en' => 'with His Name', 'meaning_ur' => 'اس کے نام کے ساتھ'],
                    ['arabic' => 'شَيْءٌ', 'transliteration' => 'shay’un', 'meaning_en' => 'anything', 'meaning_ur' => 'کوئی چیز'],
                    ['arabic' => 'فِي الْأَرْضِ', 'transliteration' => 'fī l-arḍi', 'meaning_en' => 'in the earth', 'meaning_ur' => 'زمین میں'],
                    ['arabic' => 'وَلَا فِي السَّمَاءِ', 'transliteration' => 'wa-lā fī l-samā’i', 'meaning_en' => 'nor in the heavens', 'meaning_ur' => 'اور نہ آسمان میں'],
                    ['arabic' => 'وَهُوَ', 'transliteration' => 'wa-huwa', 'meaning_en' => 'and He is', 'meaning_ur' => 'اور وہ'],
                    ['arabic' => 'السَّمِيعُ الْعَلِيمُ', 'transliteration' => 'l-Samī‘u l-‘Alīm', 'meaning_en' => 'All-Hearing, All-Knowing', 'meaning_ur' => 'سننے والا جاننے والا'],
                ],
                'meaning_explanation' => 'Invoking Allah’s sacred Name serves as an impenetrable celestial fortress. Knowing He is As-Sami‘ (hears all appeals) and Al-‘Alim (knows every hidden threat) dispels terror and instills peace.',
                'benefits_and_virtues' => 'Uthman ibn ‘Affan (RA) reported that the Prophet ﷺ said: "Any servant who recites it three times in the morning and three times in the evening will not be harmed by anything." (Sunan Abu Dawud 5088; Jami‘ at-Tirmidhi 3388).',
                'when_to_recite' => '3 times every morning and 3 times every evening',
                'repeat_count' => 3,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sunan Abu Dawud 5088; Jami‘ at-Tirmidhi 3388',
                'hadith_book' => 'Sunan Abu Dawud',
                'hadith_number' => '5088',
                'hadith_grading' => 'Hasan Sahih',
                'is_featured' => true,
                'order' => 9,
            ],
            [
                'title' => 'Dua for Guidance, God-Consciousness, Chastity, and Self-Sufficiency',
                'slug' => 'guidance-taqwa-chastity-wealth',
                'category' => 'Guidance & Knowledge',
                'description' => 'A concise supplication capturing the four foundations of a noble, protected, and independent Islamic life.',
                'arabic_text' => 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
                'transliteration' => 'Allāhumma innī as’aluka l-hudā wa-l-tuqā wa-l-‘afāfa wa-l-ghinā',
                'translation_en' => 'O Allah, I ask You for guidance, piety (Taqwa), chastity, and self-sufficiency (freedom from need).',
                'translation_ur' => 'اے اللہ! میں تجھ سے ہدایت، پرہیزگاری، پاکدامنی اور استغناء (بے نیازی) کا سوال کرتا ہوں۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'إِنِّي أَسْأَلُكَ', 'transliteration' => 'innī as’aluka', 'meaning_en' => 'I ask You', 'meaning_ur' => 'میں تجھ سے مانگتا ہوں'],
                    ['arabic' => 'الْهُدَى', 'transliteration' => 'l-hudā', 'meaning_en' => 'guidance', 'meaning_ur' => 'ہدایت'],
                    ['arabic' => 'وَالتُّقَى', 'transliteration' => 'wa-l-tuqā', 'meaning_en' => 'and piety / consciousness', 'meaning_ur' => 'اور تقویٰ'],
                    ['arabic' => 'وَالْعَفَافَ', 'transliteration' => 'wa-l-‘afāfa', 'meaning_en' => 'and chastity / purity', 'meaning_ur' => 'اور پاکدامنی'],
                    ['arabic' => 'وَالْغِنَى', 'transliteration' => 'wa-l-ghinā', 'meaning_en' => 'and richness of soul', 'meaning_ur' => 'اور دل کی بے نیازی'],
                ],
                'meaning_explanation' => 'Al-Huda is clarity of the straight path; At-Tuqa is living with awe of Allah; Al-‘Afaf is moral safeguarding and modesty; Al-Ghina is richness of the heart and freedom from relying on people.',
                'benefits_and_virtues' => 'Narrated by Abdullah ibn Mas‘ud (RA): "The Prophet ﷺ used to supplicate with these four gems..." (Sahih Muslim 2721).',
                'when_to_recite' => 'In daily prayers, before starting major ventures, and during tahajjud',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih Muslim 2721',
                'hadith_book' => 'Sahih Muslim',
                'hadith_number' => '2721',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 10,
            ],
            [
                'title' => 'Dua for Sickness and Healing (Ruqyah of the Prophet ﷺ)',
                'slug' => 'prophetic-dua-healing-sickness',
                'category' => 'Protection & Health',
                'description' => 'The supplication recited by Prophet Muhammad ﷺ when visiting the sick or treating ailments by placing his blessed right hand over the patient.',
                'arabic_text' => 'اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَاسَ، اشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
                'transliteration' => 'Allāhumma Rabba l-nās, adhhibi l-ba’s, ishfi anta l-Shāfī, lā shifā’a illā shifā’uka, shifā’an lā yughādiru saqamā',
                'translation_en' => 'O Allah, Lord of mankind, remove the disease and bring healing; You are the Healer, there is no healing except Your healing—a cure that leaves behind no illness.',
                'translation_ur' => 'اے اللہ، تمام انسانوں کے رب! بیماری کو دور فرما اور شفا عطا فرما، تو ہی شفا دینے والا ہے، تیری شفا کے سوا کوئی شفا نہیں، ایسی شفا جو کسی بیماری کو باقی نہ چھوڑے۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'رَبَّ النَّاسِ', 'transliteration' => 'Rabba l-nās', 'meaning_en' => 'Lord of mankind', 'meaning_ur' => 'انسانوں کے رب'],
                    ['arabic' => 'أَذْهِبِ الْبَاسَ', 'transliteration' => 'adhhibi l-ba’s', 'meaning_en' => 'remove the ailment', 'meaning_ur' => 'تکلیف کو دور فرما'],
                    ['arabic' => 'اشْفِ', 'transliteration' => 'ishfi', 'meaning_en' => 'heal / cure', 'meaning_ur' => 'شفا عطا فرما'],
                    ['arabic' => 'أَنْتَ الشَّافِي', 'transliteration' => 'anta l-Shāfī', 'meaning_en' => 'You are the Healer', 'meaning_ur' => 'تو ہی شفا دینے والا ہے'],
                    ['arabic' => 'لَا شِفَاءَ', 'transliteration' => 'lā shifā’a', 'meaning_en' => 'no cure exists', 'meaning_ur' => 'کوئی شفا نہیں'],
                    ['arabic' => 'إِلَّا شِفَاؤُكَ', 'transliteration' => 'illā shifā’uka', 'meaning_en' => 'except Your cure', 'meaning_ur' => 'سوائے تیری شفا کے'],
                    ['arabic' => 'شِفَاءً', 'transliteration' => 'shifā’an', 'meaning_en' => 'a total healing', 'meaning_ur' => 'ایسی شفا'],
                    ['arabic' => 'لَا يُغَادِرُ سَقَمًا', 'transliteration' => 'lā yughādiru saqamā', 'meaning_en' => 'leaves no sickness', 'meaning_ur' => 'جو کوئی بیماری نہ چھوڑے'],
                ],
                'meaning_explanation' => 'Recognizing Ash-Shafi (The Absolute Healer) aligns medical remedies with divine decree. Asking for a cure that "leaves no illness behind" seeks complete eradication of physical, mental, and relapse symptoms.',
                'benefits_and_virtues' => '‘Aisha (RA) narrated that whenever Allah’s Messenger ﷺ visited an ailing person or when an ailment was brought to him, he wiped with his right hand and recited this prayer. (Sahih al-Bukhari 5743; Sahih Muslim 2191).',
                'when_to_recite' => 'When visiting the sick, placing one’s hand on pain, or praying for physical & emotional recovery',
                'repeat_count' => 3,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih al-Bukhari 5743; Sahih Muslim 2191',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '5743',
                'hadith_grading' => 'Sahih',
                'is_featured' => true,
                'order' => 11,
            ],
            [
                'title' => 'Dua for Leaving the House (Divine Protection and Guidance)',
                'slug' => 'leaving-house-protection',
                'category' => 'Daily Living',
                'description' => 'Recited when crossing the threshold of one’s home to entrust oneself into Allah’s care, upon which angels proclaim safety and devils flee.',
                'arabic_text' => 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
                'transliteration' => 'Bismillāh, tawakkaltu ‘alā-llāh, wa-lā ḥawla wa-lā quwwata illā billāh',
                'translation_en' => 'In the name of Allah, I place my trust in Allah; there is no might and no power except with Allah.',
                'translation_ur' => 'اللہ کے نام کے ساتھ، میں نے اللہ پر بھروسہ کیا، اور برائی سے بچنے کی طاقت اور نیکی کرنے کی قوت صرف اللہ ہی کی مدد سے ہے۔',
                'word_by_word' => [
                    ['arabic' => 'بِسْمِ اللَّهِ', 'transliteration' => 'Bismillāh', 'meaning_en' => 'In the name of Allah', 'meaning_ur' => 'اللہ کے نام سے'],
                    ['arabic' => 'تَوَكَّلْتُ', 'transliteration' => 'tawakkaltu', 'meaning_en' => 'I put my full trust', 'meaning_ur' => 'میں نے بھروسہ کیا'],
                    ['arabic' => 'عَلَى اللَّهِ', 'transliteration' => '‘alā-llāh', 'meaning_en' => 'upon Allah', 'meaning_ur' => 'اللہ پر'],
                    ['arabic' => 'وَلَا حَوْلَ', 'transliteration' => 'wa-lā ḥawla', 'meaning_en' => 'and there is no power', 'meaning_ur' => 'اور کوئی تدبیر نہیں'],
                    ['arabic' => 'وَلَا قُوَّةَ', 'transliteration' => 'wa-lā quwwata', 'meaning_en' => 'and no strength', 'meaning_ur' => 'اور کوئی قوت نہیں'],
                    ['arabic' => 'إِلَّا بِاللَّهِ', 'transliteration' => 'illā billāh', 'meaning_en' => 'except through Allah', 'meaning_ur' => 'مگر اللہ ہی کے ساتھ'],
                ],
                'meaning_explanation' => 'Tawakkul is conscious reliance on Allah while taking natural steps. "La hawla wa la quwwata illa billah" surrenders all autonomy to the Creator, acknowledging that not a single movement occurs without His permission.',
                'benefits_and_virtues' => 'The Prophet ﷺ said: "When a man goes out of his house and says this, it is said to him: ‘You have been guided, defended and protected,’ and the devils turn away from him." (Sunan Abu Dawud 5095; Jami‘ at-Tirmidhi 3426).',
                'when_to_recite' => 'Every time one steps out of the house or commences a journey',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sunan Abu Dawud 5095; Jami‘ at-Tirmidhi 3426',
                'hadith_book' => 'Sunan Abu Dawud',
                'hadith_number' => '5095',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 12,
            ],
            [
                'title' => 'Dua for Spouses and Offspring (The Joy of Our Eyes)',
                'slug' => 'dua-spouses-righteous-family',
                'category' => 'Parents & Family',
                'description' => 'The supplication of the true Servants of the Most Merciful (Ibad ur-Rahman) seeking righteous companions and offspring who bring comfort to the soul.',
                'arabic_text' => 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
                'transliteration' => 'Rabbanā hab lanā min azwājinā wa-dhurriyyātinā qurrata a‘yunin wa-j‘alnā li-l-muttaqīna imāmā',
                'translation_en' => 'Our Lord, grant us from among our spouses and offspring comfort to our eyes, and make us an example for the righteous.',
                'translation_ur' => 'اے ہمارے پروردگار! ہمیں ہماری بیویوں اور ہماری اولاد کی طرف سے آنکھوں کی ٹھنڈک عطا فرما اور ہمیں پرہیزگاروں کا پیشوا بنا۔',
                'word_by_word' => [
                    ['arabic' => 'رَبَّنَا', 'transliteration' => 'Rabbanā', 'meaning_en' => 'Our Lord', 'meaning_ur' => 'اے ہمارے رب'],
                    ['arabic' => 'هَبْ لَنَا', 'transliteration' => 'hab lanā', 'meaning_en' => 'grant us / bestow', 'meaning_ur' => 'ہمیں عطا فرما'],
                    ['arabic' => 'مِنْ أَزْوَاجِنَا', 'transliteration' => 'min azwājinā', 'meaning_en' => 'from our spouses', 'meaning_ur' => 'ہمارے جیون ساتھیوں سے'],
                    ['arabic' => 'وَذُرِّيَّاتِنَا', 'transliteration' => 'wa-dhurriyyātinā', 'meaning_en' => 'and our children', 'meaning_ur' => 'اور ہماری اولاد سے'],
                    ['arabic' => 'قُرَّةَ أَعْيُنٍ', 'transliteration' => 'qurrata a‘yunin', 'meaning_en' => 'coolness / joy of eyes', 'meaning_ur' => 'آنکھوں کی ٹھنڈک'],
                    ['arabic' => 'وَاجْعَلْنَا', 'transliteration' => 'wa-j‘alnā', 'meaning_en' => 'and make us', 'meaning_ur' => 'اور ہمیں بنا دے'],
                    ['arabic' => 'لِلْمُتَّقِينَ إِمَامًا', 'transliteration' => 'li-l-muttaqīna imāmā', 'meaning_en' => 'leaders for the god-conscious', 'meaning_ur' => 'متقیوں کا پیشوا'],
                ],
                'meaning_explanation' => '"Qurrata a‘yun" (قُرَّةَ أَعْيُن) refers to tears of joy and soothing peace when witnessing one’s family worship Allah and walk the path of virtue. Asking to be an "Imam for the Muttaqin" is a noble ambition to lead in good deeds and humility.',
                'benefits_and_virtues' => 'Mentioned in Surah Al-Furqan (25:74) as the defining characteristic of those who inherit the lofty mansions of Paradise (Al-Ghurfah).',
                'when_to_recite' => 'Daily, in prostration, and when praying for marriage, peace in the home, or children',
                'repeat_count' => 3,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Al-Furqan (25:74)',
                'surah_number' => 25,
                'verse_number' => 74,
                'hadith_reference' => null,
                'hadith_book' => null,
                'hadith_number' => null,
                'hadith_grading' => null,
                'is_featured' => true,
                'order' => 13,
            ],
            [
                'title' => 'Dua for Gratitude and Continuing Good Deeds',
                'slug' => 'gratitude-righteous-deeds-sulaiman',
                'category' => 'Praise & Gratitude',
                'description' => 'The prayer of Prophet Sulaiman (Solomon) AS upon recognizing Allah’s immense favors, pleading for divine inspiration to stay grateful and act righteously.',
                'arabic_text' => 'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ',
                'transliteration' => 'Rabbi awzi‘nī an ashkura ni‘mataka-llatī an‘amta ‘alayya wa-‘alā wālidayya wa-an a‘mala ṣāliḥan tarḍāhu wa-adkhilnī bi-raḥmatika fī ‘ibādika l-ṣāliḥīn',
                'translation_en' => 'My Lord, inspire me to be grateful for Your favor which You have bestowed upon me and upon my parents, and to do righteous work that will please You, and admit me by Your mercy into [the ranks of] Your righteous servants.',
                'translation_ur' => 'اے میرے رب! مجھے توفیق عطا فرما کہ میں تیری ان نعمتوں کا شکر ادا کروں جو تو نے مجھ پر اور میرے والدین پر فرمائی ہیں، اور ایسا نیک عمل کروں جس سے تو راضی ہو جائے، اور مجھے اپنی رحمت سے اپنے نیک بندوں میں داخل فرما۔',
                'word_by_word' => [
                    ['arabic' => 'رَبِّ أَوْزِعْنِي', 'transliteration' => 'Rabbi awzi‘nī', 'meaning_en' => 'My Lord, inspire me', 'meaning_ur' => 'اے میرے رب مجھے توفیق دے'],
                    ['arabic' => 'أَنْ أَشْكُرَ', 'transliteration' => 'an ashkura', 'meaning_en' => 'to be grateful', 'meaning_ur' => 'کہ میں شکر ادا کروں'],
                    ['arabic' => 'نِعْمَتَكَ', 'transliteration' => 'ni‘mataka', 'meaning_en' => 'for Your favor', 'meaning_ur' => 'تیری نعمت کا'],
                    ['arabic' => 'الَّتِي أَنْعَمْتَ عَلَيَّ', 'transliteration' => 'allatī an‘amta ‘alayya', 'meaning_en' => 'bestowed on me', 'meaning_ur' => 'جو تو نے مجھ پر کی'],
                    ['arabic' => 'وَعَلَىٰ وَالِدَيَّ', 'transliteration' => 'wa-‘alā wālidayya', 'meaning_en' => 'and upon my parents', 'meaning_ur' => 'اور میرے والدین پر'],
                    ['arabic' => 'وَأَنْ أَعْمَلَ صَالِحًا', 'transliteration' => 'wa-an a‘mala ṣāliḥan', 'meaning_en' => 'and do righteous deeds', 'meaning_ur' => 'اور ایسے نیک عمل کروں'],
                    ['arabic' => 'تَرْضَاهُ', 'transliteration' => 'tarḍāhu', 'meaning_en' => 'pleasing to You', 'meaning_ur' => 'جس سے تو راضی ہو'],
                    ['arabic' => 'وَأَدْخِلْنِي بِرَحْمَتِكَ', 'transliteration' => 'wa-adkhilnī bi-raḥmatika', 'meaning_en' => 'admit me by Your mercy', 'meaning_ur' => 'اور مجھے اپنی رحمت سے داخل فرما'],
                    ['arabic' => 'فِي عِبَادِكَ الصَّالِحِينَ', 'transliteration' => 'fī ‘ibādika l-ṣāliḥīn', 'meaning_en' => 'among righteous servants', 'meaning_ur' => 'اپنے نیک بندوں میں'],
                ],
                'meaning_explanation' => '"Awzi‘nī" (أَوْزِعْنِي) is a pleading to restrain one’s baser desires and infuse the soul with continuous alertness of gratitude. Notice that entry into Paradise is explicitly attributed to divine Rahmah (mercy), not one’s deeds alone.',
                'benefits_and_virtues' => 'Found in both Surah An-Naml (27:19) and Surah Al-Ahqaf (46:15) as the ideal prayer when reaching maturity and reflecting upon life achievements.',
                'when_to_recite' => 'Upon receiving blessings, career success, milestones in life, and after prayers',
                'repeat_count' => 1,
                'source_type' => 'quran',
                'quran_reference' => 'Surah An-Naml (27:19)',
                'surah_number' => 27,
                'verse_number' => 19,
                'hadith_reference' => null,
                'hadith_book' => null,
                'hadith_number' => null,
                'hadith_grading' => null,
                'is_featured' => false,
                'order' => 14,
            ],
            [
                'title' => 'Dua for Acceptance of Deeds (Ibrahim and Ismail AS)',
                'slug' => 'dua-acceptance-deeds-ibrahim',
                'category' => 'Praise & Gratitude',
                'description' => 'Supplicated by Prophets Ibrahim and Ismail (peace be upon them) while elevating the sacred foundations of the Ka‘bah in Makkah.',
                'arabic_text' => 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
                'transliteration' => 'Rabbanā taqabbal minnā innaka anta l-Samī‘u l-‘Alīm',
                'translation_en' => 'Our Lord, accept [this] from us. Indeed You are the All-Hearing, the All-Knowing.',
                'translation_ur' => 'اے ہمارے پروردگار! ہم سے (یہ خدمت) قبول فرما، بے شک تو ہی سب کچھ سننے والا، سب کچھ جاننے والا ہے۔',
                'word_by_word' => [
                    ['arabic' => 'رَبَّنَا', 'transliteration' => 'Rabbanā', 'meaning_en' => 'Our Lord', 'meaning_ur' => 'اے ہمارے رب'],
                    ['arabic' => 'تَقَبَّلْ مِنَّا', 'transliteration' => 'taqabbal minnā', 'meaning_en' => 'accept from us', 'meaning_ur' => 'ہم سے قبول فرما'],
                    ['arabic' => 'إِنَّكَ أَنتَ', 'transliteration' => 'innaka anta', 'meaning_en' => 'indeed You are', 'meaning_ur' => 'بے شک تو ہی ہے'],
                    ['arabic' => 'السَّمِيعُ الْعَلِيمُ', 'transliteration' => 'l-Samī‘u l-‘Alīm', 'meaning_en' => 'All-Hearing, All-Knowing', 'meaning_ur' => 'سننے والا جاننے والا'],
                ],
                'meaning_explanation' => 'Despite executing the greatest architectural and spiritual task on earth by direct divine decree, Ibrahim (AS) did not display self-satisfaction. Instead, he trembled with humility, begging for acceptance.',
                'benefits_and_virtues' => 'Classical scholar Wuhaib ibn al-Ward wept when reciting this verse, stating: "O Friend of the Most Merciful! You built the House of the Rahman, yet you feared it would not be accepted!" Essential after every prayer and good deed.',
                'when_to_recite' => 'After completing any act of worship (Salah, Quran reading, Sadaqah, fasting, building)',
                'repeat_count' => 3,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Al-Baqarah (2:127)',
                'surah_number' => 2,
                'verse_number' => 127,
                'hadith_reference' => null,
                'hadith_book' => null,
                'hadith_number' => null,
                'hadith_grading' => null,
                'is_featured' => false,
                'order' => 15,
            ],
            [
                'title' => 'Dua in Sajdah for Total Forgiveness (Minor, Major, Past, and Future)',
                'slug' => 'prostration-dua-total-forgiveness',
                'category' => 'Forgiveness & Tawbah',
                'description' => 'The deep supplication whispered by Prophet Muhammad ﷺ in prostration, seeking eradication of all sins across time, magnitude, and intention.',
                'arabic_text' => 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ: دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ',
                'transliteration' => 'Allāhumma-ghfir lī dhanbī kullahu: diqqahu wa-jillahu, wa-awwalahu wa-ākhirahu, wa-‘alāniyatahu wa-sirrahu',
                'translation_en' => 'O Allah, forgive all my sins: the minor and the major, the first and the last, the public and the hidden.',
                'translation_ur' => 'اے اللہ! میرے تمام گناہ معاف فرما دے: چھوٹے اور بڑے، پہلے اور پچھلے، ظاہر اور پوشیدہ۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ اغْفِرْ لِي', 'transliteration' => 'Allāhumma-ghfir lī', 'meaning_en' => 'O Allah forgive me', 'meaning_ur' => 'اے اللہ مجھے بخش دے'],
                    ['arabic' => 'ذَنْبِي كُلَّهُ', 'transliteration' => 'dhanbī kullahu', 'meaning_en' => 'all my sins', 'meaning_ur' => 'میرے تمام گناہ'],
                    ['arabic' => 'دِقَّهُ وَجِلَّهُ', 'transliteration' => 'diqqahu wa-jillahu', 'meaning_en' => 'minor and major', 'meaning_ur' => 'چھوٹے اور بڑے'],
                    ['arabic' => 'وَأَوَّلَهُ وَآخِرَهُ', 'transliteration' => 'wa-awwalahu wa-ākhirahu', 'meaning_en' => 'first and last', 'meaning_ur' => 'پہلے اور پچھلے'],
                    ['arabic' => 'وَعَلَانِيَتَهُ وَسِرَّهُ', 'transliteration' => 'wa-‘alāniyatahu wa-sirrahu', 'meaning_en' => 'open and secret', 'meaning_ur' => 'کھلے اور چھپے'],
                ],
                'meaning_explanation' => 'Prostration (Sujud) is the spiritual posture where the servant is closest to Allah. This prayer methodically leaves no category of imperfection uncovered before the Divine Forgiver.',
                'benefits_and_virtues' => 'Abu Hurairah (RA) reported that the Messenger of Allah ﷺ used to say in his prostration: "Allahumma ighfir li dhanbi kullahu..." (Sahih Muslim 483).',
                'when_to_recite' => 'During Sajdah in obligatory and voluntary prayers',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih Muslim 483',
                'hadith_book' => 'Sahih Muslim',
                'hadith_number' => '483',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 16,
            ],
            [
                'title' => 'Dua for Spiritual Light in All Faculties (Dua an-Nur)',
                'slug' => 'dua-an-nur-spiritual-light',
                'category' => 'Guidance & Knowledge',
                'description' => 'The majestic prayer of the Prophet ﷺ on the way to the mosque and in night prayers, begging Allah to envelop every dimension of the body and mind in divine celestial illumination (Nur).',
                'arabic_text' => 'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا، وَفِي بَصَرِي نُورًا، وَفِي سَمْعِي نُورًا، وَعَنْ يَمِينِي نُورًا، وَعَنْ يَسَارِي نُورًا، وَفَوْقِي نُورًا، وَتَحْتِي نُورًا، وَأَمَامِي نُورًا، وَخَلْفِي نُورًا، وَاجْعَلْ لِي نُورًا',
                'transliteration' => 'Allāhumma-j‘al fī qalbī nūrā, wa-fī baṣarī nūrā, wa-fī sam‘ī nūrā, wa-‘an yamīnī nūrā, wa-‘an yasārī nūrā, wa-fawqī nūrā, wa-taḥtī nūrā, wa-amāmī nūrā, wa-khalfī nūrā, wa-j‘al lī nūrā',
                'translation_en' => 'O Allah, place light in my heart, light in my sight, light in my hearing, light to my right, light to my left, light above me, light below me, light in front of me, light behind me, and grant me light.',
                'translation_ur' => 'اے اللہ! میرے دل میں نور پیدا فرما، اور میری آنکھوں میں نور، اور میرے کانوں میں نور، اور میرے دائیں جانب نور، اور میرے بائیں جانب نور، اور میرے اوپر نور، اور میرے نیچے نور، اور میرے آگے نور، اور میرے پیچھے نور، اور مجھے نور بنا دے۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ اجْعَلْ', 'transliteration' => 'Allāhumma-j‘al', 'meaning_en' => 'O Allah place', 'meaning_ur' => 'اے اللہ رکھ دے'],
                    ['arabic' => 'فِي قَلْبِي نُورًا', 'transliteration' => 'fī qalbī nūrā', 'meaning_en' => 'light in my heart', 'meaning_ur' => 'میرے دل میں نور'],
                    ['arabic' => 'وَفِي بَصَرِي نُورًا', 'transliteration' => 'wa-fī baṣarī nūrā', 'meaning_en' => 'light in my sight', 'meaning_ur' => 'میری آنکھوں میں نور'],
                    ['arabic' => 'وَفِي سَمْعِي نُورًا', 'transliteration' => 'wa-fī sam‘ī nūrā', 'meaning_en' => 'light in my hearing', 'meaning_ur' => 'میرے کانوں میں نور'],
                    ['arabic' => 'وَعَنْ يَمِينِي نُورًا', 'transliteration' => 'wa-‘an yamīnī nūrā', 'meaning_en' => 'light on my right', 'meaning_ur' => 'میرے دائیں نور'],
                    ['arabic' => 'وَعَنْ يَسَارِي نُورًا', 'transliteration' => 'wa-‘an yasārī nūrā', 'meaning_en' => 'light on my left', 'meaning_ur' => 'میرے بائیں نور'],
                    ['arabic' => 'وَفَوْقِي نُورًا', 'transliteration' => 'wa-fawqī nūrā', 'meaning_en' => 'light above me', 'meaning_ur' => 'میرے اوپر نور'],
                    ['arabic' => 'وَتَحْتِي نُورًا', 'transliteration' => 'wa-taḥtī nūrā', 'meaning_en' => 'light below me', 'meaning_ur' => 'میرے نیچے نور'],
                    ['arabic' => 'وَأَمَامِي نُورًا', 'transliteration' => 'wa-amāmī nūrā', 'meaning_en' => 'light before me', 'meaning_ur' => 'میرے آگے نور'],
                    ['arabic' => 'وَخَلْفِي نُورًا', 'transliteration' => 'wa-khalfī nūrā', 'meaning_en' => 'light behind me', 'meaning_ur' => 'میرے پیچھے نور'],
                    ['arabic' => 'وَاجْعَلْ لِي نُورًا', 'transliteration' => 'wa-j‘al lī nūrā', 'meaning_en' => 'and amplify light for me', 'meaning_ur' => 'اور مجھے نور عطا فرما'],
                ],
                'meaning_explanation' => 'Nur in this context is divine perception that pierces delusions, guides decisions to truth, and protects against dark distractions and doubts in this world and on the Day of Judgment.',
                'benefits_and_virtues' => 'Narrated by Ibn Abbas (RA) during his stay in the house of the Prophet ﷺ while witnessing Tahajjud. (Sahih al-Bukhari 6316; Sahih Muslim 763).',
                'when_to_recite' => 'During Tahajjud, when walking to the mosque, and when starting daily learning',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih al-Bukhari 6316; Sahih Muslim 763',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '6316',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 17,
            ],
            [
                'title' => 'Dua Before Sleep and Upon Waking Up',
                'slug' => 'dua-sleep-waking',
                'category' => 'Daily Living',
                'description' => 'The Sunnah formulas declaring that sleep is a minor death and awakening is an act of divine resurrection, sanctified with the name of Allah.',
                'arabic_text' => 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا ... الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
                'transliteration' => 'Bi-smika Allāhumma amūtu wa-aḥyā ... Al-ḥamdu li-llāhi-lladhī aḥyānā ba‘da mā amātanā wa-ilayhi l-nushūr',
                'translation_en' => 'In Your Name, O Allah, I die and I live. ... All praise is due to Allah, Who gave us life after having caused us to die, and to Him is the ultimate resurrection.',
                'translation_ur' => 'اے اللہ! تیرے نام کے ساتھ میں مرتا اور جیتا ہوں ... تمام تعریفیں اللہ کے لیے ہیں جس نے ہمیں مارنے کے بعد زندہ کیا اور اسی کی طرف اٹھ کر جانا ہے۔',
                'word_by_word' => [
                    ['arabic' => 'بِاسْمِكَ', 'transliteration' => 'Bi-smika', 'meaning_en' => 'In Your Name', 'meaning_ur' => 'تیرے نام کے ساتھ'],
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'أَمُوتُ وَأَحْيَا', 'transliteration' => 'amūtu wa-aḥyā', 'meaning_en' => 'I die and I live', 'meaning_ur' => 'میں مرتا اور جیتا ہوں'],
                    ['arabic' => 'الْحَمْدُ لِلَّهِ', 'transliteration' => 'Al-ḥamdu li-llāh', 'meaning_en' => 'All praise to Allah', 'meaning_ur' => 'تمام تعریفیں اللہ کے لیے'],
                    ['arabic' => 'الَّذِي أَحْيَانَا', 'transliteration' => 'alladhī aḥyānā', 'meaning_en' => 'Who gave us life', 'meaning_ur' => 'جس نے ہمیں زندگی دی'],
                    ['arabic' => 'بَعْدَ مَا أَمَاتَنَا', 'transliteration' => 'ba‘da mā amātanā', 'meaning_en' => 'after causing us to die', 'meaning_ur' => 'ہمیں موت دینے کے بعد'],
                    ['arabic' => 'وَإِلَيْهِ النُّشُورُ', 'transliteration' => 'wa-ilayhi l-nushūr', 'meaning_en' => 'and to Him is resurrection', 'meaning_ur' => 'اور اسی کی طرف لوٹنا ہے'],
                ],
                'meaning_explanation' => 'Sleep is named a "minor death" in the Quran (39:42). Opening and closing consciousness with Allah’s remembrance frames every day inside sacred mindfulness.',
                'benefits_and_virtues' => 'Hudhaifah ibn al-Yaman (RA) reported: "Whenever the Prophet ﷺ intended to go to bed, he would recite: Bismika Allahumma amutu wa ahya. And upon waking, he said: Al-hamdu lillahil-ladhi ahyana..." (Sahih al-Bukhari 6324).',
                'when_to_recite' => 'Immediately prior to sleeping and immediately upon opening the eyes in the morning',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Sahih al-Bukhari 6324',
                'hadith_book' => 'Sahih al-Bukhari',
                'hadith_number' => '6324',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 18,
            ],
            [
                'title' => 'Rabbi Inni Zalamtu Nafsi (Dua of Prophet Musa for Instant Forgiveness)',
                'slug' => 'prophet-musa-instant-forgiveness',
                'category' => 'Forgiveness & Tawbah',
                'description' => 'The urgent, heart-wrenching repentance of Prophet Musa (AS) after an unintended fatality in Egypt. Allah immediately accepted his repentance and wiped his slate clean.',
                'arabic_text' => 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي فَغَفَرَ لَهُ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
                'transliteration' => 'Rabbi innī ẓalamtu nafsī fa-ghfir lī fa-ghafara lah, innahu huwa l-Ghafūru l-Raḥīm',
                'translation_en' => 'My Lord, indeed I have wronged myself, so forgive me, and He forgave him. Indeed, He is the Forgiving, the Merciful.',
                'translation_ur' => 'اے میرے رب! بے شک میں نے اپنی جان پر ظلم کیا، پس تو مجھے معاف فرما دے؛ چنانچہ اس نے اسے معاف فرما دیا، بے شک وہی بڑا بخشنے والا، نہایت رحم فرمانے والا ہے۔',
                'word_by_word' => [
                    ['arabic' => 'رَبِّ', 'transliteration' => 'Rabbi', 'meaning_en' => 'My Lord', 'meaning_ur' => 'اے میرے رب'],
                    ['arabic' => 'إِنِّي', 'transliteration' => 'innī', 'meaning_en' => 'indeed I', 'meaning_ur' => 'بے شک میں نے'],
                    ['arabic' => 'ظَلَمْتُ نَفْسِي', 'transliteration' => 'ẓalamtu nafsī', 'meaning_en' => 'wronged myself', 'meaning_ur' => 'اپنی جان پر ظلم کیا'],
                    ['arabic' => 'فَاغْفِرْ لِي', 'transliteration' => 'fa-ghfir lī', 'meaning_en' => 'so forgive me', 'meaning_ur' => 'پس مجھے معاف کر دے'],
                    ['arabic' => 'فَغَفَرَ لَهُ', 'transliteration' => 'fa-ghafara lahu', 'meaning_en' => 'and He forgave him', 'meaning_ur' => 'تو اس نے اسے معاف کر دیا'],
                    ['arabic' => 'إِنَّهُ هُوَ', 'transliteration' => 'innahu huwa', 'meaning_en' => 'indeed He is', 'meaning_ur' => 'بے شک وہی'],
                    ['arabic' => 'الْغَفُورُ الرَّحِيمُ', 'transliteration' => 'l-Ghafūru l-Raḥīm', 'meaning_en' => 'All-Forgiving, Merciful', 'meaning_ur' => 'بخشنے والا مہربان'],
                ],
                'meaning_explanation' => 'Musa (AS) did not justify his mistake or offer excuses; he immediately confessed "I wronged myself". The grammatical "fa" in "fa-ghafara lahu" demonstrates instant divine forgiveness without delay.',
                'benefits_and_virtues' => 'Recorded in Surah Al-Qasas (28:16), teaching that no matter the magnitude of one’s error or regret, immediate remorse and direct confession to Allah brings immediate pardon.',
                'when_to_recite' => 'Immediately after committing any sin, experiencing remorse, and during repentance',
                'repeat_count' => 3,
                'source_type' => 'quran',
                'quran_reference' => 'Surah Al-Qasas (28:16)',
                'surah_number' => 28,
                'verse_number' => 16,
                'hadith_reference' => null,
                'hadith_book' => null,
                'hadith_number' => null,
                'hadith_grading' => null,
                'is_featured' => false,
                'order' => 19,
            ],
            [
                'title' => 'Dua for Good Character and Inner Purification',
                'slug' => 'good-character-inner-purification',
                'category' => 'Guidance & Knowledge',
                'description' => 'The supplication asking Allah to beautify one’s inner morals, ethics, and temper just as He beautified the physical creation.',
                'arabic_text' => 'اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
                'transliteration' => 'Allāhumma kamā ḥassanta khalqī fa-ḥassin khuluqī',
                'translation_en' => 'O Allah, just as You have made my external form good, make my character and manners good.',
                'translation_ur' => 'اے اللہ! جس طرح تو نے میری ظاہری صورت کو خوبصورت بنایا، اسی طرح میرے اخلاق و کردار کو بھی سنوار دے۔',
                'word_by_word' => [
                    ['arabic' => 'اللَّهُمَّ', 'transliteration' => 'Allāhumma', 'meaning_en' => 'O Allah', 'meaning_ur' => 'اے اللہ'],
                    ['arabic' => 'كَمَا', 'transliteration' => 'kamā', 'meaning_en' => 'just as', 'meaning_ur' => 'جیسا کہ'],
                    ['arabic' => 'حَسَّنْتَ', 'transliteration' => 'ḥassanta', 'meaning_en' => 'You beautified', 'meaning_ur' => 'تو نے اچھا بنایا'],
                    ['arabic' => 'خَلْقِي', 'transliteration' => 'khalqī', 'meaning_en' => 'my physical creation', 'meaning_ur' => 'میری تخلیق / صورت کو'],
                    ['arabic' => 'فَحَسِّنْ', 'transliteration' => 'fa-ḥassin', 'meaning_en' => 'so beautify', 'meaning_ur' => 'پس اچھا بنا دے'],
                    ['arabic' => 'خُلُقِي', 'transliteration' => 'khuluqī', 'meaning_en' => 'my inner character/manners', 'meaning_ur' => 'میرے اخلاق کو'],
                ],
                'meaning_explanation' => 'Distinguishing between Khalq (خَلْق - physical shape) and Khuluq (خُلُق - moral disposition). True beauty in Islam is the harmony of righteous etiquette, kindness, patience, and integrity.',
                'benefits_and_virtues' => 'Prophet Muhammad ﷺ said: "The heaviest thing placed on the Scale of the believer on the Day of Resurrection will be good character." (Jami‘ at-Tirmidhi 2002; Musnad Ahmad 24392).',
                'when_to_recite' => 'When looking in the mirror, before interacting with difficult people, and in daily prayers',
                'repeat_count' => 1,
                'source_type' => 'hadith',
                'quran_reference' => null,
                'surah_number' => null,
                'verse_number' => null,
                'hadith_reference' => 'Musnad Ahmad 24392; Sahih Ibn Hibban 959',
                'hadith_book' => 'Musnad Ahmad',
                'hadith_number' => '24392',
                'hadith_grading' => 'Sahih',
                'is_featured' => false,
                'order' => 20,
            ],
        ];

        foreach ($duas as $duaData) {
            // Find existing verse_id if surah and verse numbers are provided
            if (!empty($duaData['surah_number']) && !empty($duaData['verse_number'])) {
                $verse = DB::table('verses')
                    ->join('surahs', 'verses.surah_id', '=', 'surahs.id')
                    ->where('surahs.number', $duaData['surah_number'])
                    ->where('verses.verse_number', $duaData['verse_number'])
                    ->select('verses.id')
                    ->first();

                if ($verse) {
                    $duaData['verse_id'] = $verse->id;
                }
            }

            Dua::updateOrCreate(
                ['slug' => $duaData['slug']],
                $duaData
            );
        }
    }
}
